import ExpandLessIcon from "@mui/icons-material/ExpandLess";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import SortIcon from "@mui/icons-material/Sort";
import {
  DataGrid,
  GridPagination,
  GridToolbarContainer,
  GridToolbarQuickFilter,
  gridPageCountSelector,
  isAutogeneratedRow,
  useGridApiContext,
  useGridSelector,
} from "@mui/x-data-grid";
import { useEffect, useState } from "react";
import MuiPagination from "@mui/material/Pagination";
import {
  Close,
  Download,
  Edit,
  LocalShipping,
  Refresh,
  Visibility,
} from "@mui/icons-material";
import {
  Button,
  IconButton,
  Tooltip,
  Typography,
  Modal,
  Box,
  Chip,
  Fab,
} from "@mui/material";
import { Workbook } from "exceljs";
import LoadingScreenBlue from "../../components/ui/LoadingScreenBlue";
import { useAuthStore } from "../../hooks";
import { useProductOrder } from "../../hooks/useProductOrder";
import { localDate } from "../../Utils/ConvertIsoDate";
import Grid from "@mui/material/Grid2";
import AssignRoute from "../MyStoreHouse/ AssignRoute";
import { bgcolor, borderRadius } from "@mui/system";
import { blue, green, grey } from "@mui/material/colors";
import { useUsers } from "../../hooks/useUsers";
import DetailAssignRoute from "../MyStoreHouse/DetailAssignRoute";

const style = {
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: 800,
  bgcolor: "background.paper",
  borderRadius:'15px',
  p: 4,
};

function Pagination({ page, onPageChange, className }) {
  const apiRef = useGridApiContext();
  const pageCount = useGridSelector(apiRef, gridPageCountSelector);

  return (
    <MuiPagination
      color="primary"
      className={className}
      count={pageCount}
      page={page + 1}
      onChange={(event, newPage) => {
        onPageChange(event, newPage - 1);
      }}
    />
  );
}
export function SortedDescendingIcon() {
  return <ExpandMoreIcon className="icon" />;
}

export function SortedAscendingIcon() {
  return <ExpandLessIcon className="icon" />;
}

export function UnsortedIcon() {
  return <SortIcon className="icon" />;
}

function CustomPagination(props) {
  return <GridPagination ActionsComponent={Pagination} {...props} />;
}

const ReadyToSend = ({rows = [], loading = false, type = 0}) => {

  const [openModal, setOpenModal] = useState({ value: false, selectedPO: {}, updateUser: false, updateGuide: false });
  const [openDetail, setOpenDetail] = useState({value: false, selectedPO:{}});
  const {loadCarrierDrivers, CarrierDrivers} = useUsers()

  const handleOpen = (data, edit) =>{
    loadCarrierDrivers()
    if (updateUser === true ) {
      setOpenModal({ value: true, selectedPO: { data }, updateUser: true })
    }
    else if( updateGuide === true){
      setOpenModal({ value: true, selectedPO: { data }, updateGuide: true })
    }
    else{
      setOpenModal({ value: true, selectedPO: { data } })
    }
  }

  const handleOpenDetail = (data) =>{
    loadCarrierDrivers()
    setOpenDetail({ value: true, selectedPO: { data } })
    
  }

  const handleOpenGuide = (data) =>{
    setOpenModal({ value: true, selectedPO: { data }, updateGuide: true })
    
  }
  const handleOpenUser = (data) =>{
    setOpenModal({ value: true, selectedPO: { data }, updateUser: true })
    
  }

  const handleClose = () => setOpenModal({ value: false, selectedPO: {} });

  const handleCloseDetail = () => setOpenDetail({ value: false, selectedPO: {} });

  const exportToExcel = () => {
    const workbook = new Workbook();
    const worksheet = workbook.addWorksheet("Productos");

    // Agregar encabezados de columna
    const headerRow = worksheet.addRow([
      "Nombre del producto",
      "Descripción",
      "Precio",
      "Tamaño",
      "Código",
    ]);
    headerRow.eachCell((cell) => {
      cell.font = { bold: true };
    });

    // Agregar datos de las filas
    rows.forEach((row) => {
      worksheet.addRow([
        row.name,
        row.description,
        row.price,
        row.size,
        row.tag,
      ]);
    });

    // Crear un Blob con el archivo Excel y guardarlo
    workbook.xlsx.writeBuffer().then((buffer) => {
      const blob = new Blob([buffer], {
        type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      });
      saveAs(blob, "productos.xlsx");
    });
  };

  function CustomToolbar() {
    const apiRef = useGridApiContext();

    const handleGoToPage1 = () => apiRef.current.setPage(1);

    return (
      <GridToolbarContainer sx={{ justifyContent: "space-between" }}>
        <Button onClick={handleGoToPage1}>Regresa a la pagina 1</Button>
        <GridToolbarQuickFilter placeholder="Buscar" />
        <Button
          variant="text"
          startIcon={<Download />}
          disableElevation
          sx={{ color: "secondary" }}
          onClick={exportToExcel}
        >
          Descargar Excel
        </Button>
      </GridToolbarContainer>
    );
  }

  if (loading) return <LoadingScreenBlue />;

  const renderChip = (data) =>{
    if (!!data.route_detail === false) {
      return( 
        <Chip variant="outlined" label='No asignada' sx={{bgcolor:grey[200]}}/>
      )
    }else if (!!data.route_detail.guide === true){
      return(
        <Chip variant="outlined"  label='Asignada a compañía' sx={{bgcolor:blue[400]}} />
      )
    }else{
      return(
        <Chip variant="outlined"  label =  'Assignada a usuario' sx={{bgcolor:green[500]}} />
      )
    }
  }

  const renderOptions = (data) =>{
    if (!!data.route_detail === false) {
      return[
        <Tooltip title="Asignar compañía de envios">
        <Button
          aria-label="Asignar envio"
          color="success"
          startIcon={<LocalShipping />}
          onClick={() => handleOpen(data) }
        >
          Asignar
        </Button>
      </Tooltip>,
      <Tooltip title="Ver detalle">
      <IconButton
        aria-label="Ver detalle"
        color="primary"
        onClick={() => handleOpenDetail(data)}
      >
        <Visibility />
      </IconButton>
    </Tooltip>,
      ]
    }else if (!!data.route_detail.guide === true){
      return[
        <Tooltip title="Editar guia de envío">
        <Button
          aria-label="Asignar envio"
          color="info"
          startIcon={<Edit />}
          onClick={() => handleOpenGuide(data) }
        >
          Editar
        </Button>
      </Tooltip>,
      <Tooltip title="Ver detalle">
      <IconButton
        aria-label="Ver detalle"
        color="primary"
        onClick={() => handleOpenDetail(data)}
      >
        <Visibility />
      </IconButton>
    </Tooltip>,
      ]
    }else{
      return[
        <Tooltip title="Cambiar usuario">
        <Button
          aria-label="Cambiar usuario"
          color="info"
          startIcon={<Edit />}
          onClick={() => handleOpenUser(data, true) }
        >
          Editar
        </Button>
      </Tooltip>,
      <Tooltip title="Ver detalle">
      <IconButton
        aria-label="Ver detalle"
        color="primary"
        onClick={() => handleOpenDetail(data)}
      >
        <Visibility />
      </IconButton>
    </Tooltip>,
      ]
    }
  }


  return (
    <Grid container gap={2} maxWidth={"85vw"}>
      <DataGrid
        sx={{ fontSize: "20px", fontFamily: "BikoBold" }}
        columns={[
          {
            field: "date",
            headerName: "Fecha de compra",
            flex: 1,
            align: "center",
          },
          {
            field: "order_id",
            hideable: false,
            headerName: "Folio",
            flex: 1,
            sortable: false,
          },
          {
            field: "supply_date",
            headerName: "Fecha de empaque",
            flex: 1,
            align: "center",
          },
          {
            field: "route_detail",
            headerName: "Detalle de ruta",
            flex: 1,
            hideable: type === 0 ? false :true,
            align: "center",
            renderCell:(params)=>
              renderChip(params.row)
            
          },
          {
            field: "Opciones",
            headerName: "Opciones",
            align: "center",
            flex: 1,
            sortable: false,
            type: "actions",
            getActions: (params) => renderOptions(params.row)
          },
        ]}
        initialState={{
          sorting: {
            sortModel: [{ field: "createdAt", sort: "desc" }],
          },
          pagination: {
            paginationModel: { pageSize: 20 },
          },
        }}
        density="compact"
        rows={rows}
        pagination
        slots={{
          pagination: CustomPagination,
          toolbar: CustomToolbar,
          columnSortedDescendingIcon: SortedDescendingIcon,
          columnSortedAscendingIcon: SortedAscendingIcon,
          columnUnsortedIcon: UnsortedIcon,
        }}
        disableColumnFilter
        disableColumnMenu
        disableColumnSelector
        disableDensitySelector
        slotProps={{
          toolbar: {
            showQuickFilter: true,
            quickFilterProps: { debounceMs: 500 },
          },
        }}
        printOptions={{
          hideFooter: true,
          hideToolbar: true,
        }}
        style={{ fontFamily: "sans-serif", fontSize: "15px" }}
      />

      <Modal
        open={openModal.value}
        onClose={(event, reason) => {
          if (reason !== 'backdropClick') {
            handleClose(event);  // Solo cerrar si no es un clic en el backdrop
          }
        }}
        aria-labelledby="modal-modal-title"
        aria-describedby="modal-modal-description"
        
      >
        <Box sx={{...style}}>
        <AssignRoute productOrder={openModal.selectedPO} handleClose={handleClose} carrierDrivers={CarrierDrivers} updateUser={openModal.updateUser} updateGuide={openModal.updateGuide} />
        </Box>
      </Modal>
      <Modal
        open={openDetail.value}
        onClose={(event, reason) => {
          if (reason !== 'backdropClick') {
            handleClose(event);  // Solo cerrar si no es un clic en el backdrop
          }
        }}
        aria-labelledby="modal-modal-title"
        aria-describedby="modal-modal-description"
        
      >
        <Box sx={{...style}}>
        <Fab
        color="secondary"
        onClick={()=>handleCloseDetail()}
        sx={{position:'absolute', top:4, right:4}}
        
      >
        <Close />
      </Fab>
        <DetailAssignRoute productOrder={openDetail.selectedPO} carrierDrivers={CarrierDrivers} />
        </Box>
      </Modal>
    </Grid>
  );
};

export default ReadyToSend;
